version: 1
server:
  host: 127.0.0.1
  ws_port: 8080
  app_name: test-app
  open_browser: true
  verbosity: quiet
logs:
  dir: logdir
sources:
- name: ACCELERMETER
  type: uart
  port: /dev/cu.debug-console
  baudrate: 115200
- name: GYRO
  type: udp
  port: 6000
- name: STM
  type: uart
  port: /dev/cu.Bluetooth-Incoming-Port
  baudrate: 115200
tabs:
- label: SENSORS
  panes:
  - ACCELERMETER
  - GYRO
- label: MCU
  panes:
  - STM
